### ISSUE TITLE
Not open when we drag 1 line to open in gihub

### ISSUE THREAD

**Issue by chuongmep** [neuecc/Open-on-GitHub#13]
Hi @neuecc 
I see it just open correct location when we drag more than 2 line, I believe that we need fix for problem when case we are in location of this line.

**Comment by neuecc** [comment]
in my environment, it works 1 line and more than two lines.
could you provide more details?

**Comment by chuongmep** [comment]
Hi @neuecc, many for your reply
My inviroment it not working now, some infomation : 
- Visual Studio Version : 2022
- Window 10 21H2 
Image to see clear problem : 
![devenv_1csqIK7Whc](https://user-images.githubusercontent.com/31106432/199380194-abf866dd-83f2-4d16-b8b4-e2a594314d7d.gif)
