### ISSUE TITLE
Open on GitHub is no longer an option in json files?

### ISSUE THREAD

**Issue by tsong-wallis** [neuecc/Open-on-GitHub#14]
The Open on GitHub context menu is missing from json files in VS 2002 on Win 11. Any idea why?

Microsoft Visual Studio Professional 2022
Version 17.4.2

<img width="290" alt="image" src="https://user-images.githubusercontent.com/90782345/205394998-6aacf75e-58b8-494b-8157-914e5591100b.png">

**Comment by neuecc** [comment]
released v2.0.1
