### ISSUE TITLE
Add support for Solution Explorer and Tab Bar

### ISSUE THREAD

**Issue by ES0T** [neuecc/Open-on-GitHub#16]
It would be really nice if you could right click a file in either the Solution Explorer or in the Tab Bar and select the "Open in Git Hub". To me, the Solution Explorer and Tab Bar are places I more naturally think to look to access this functionality versus the editor window.

Thanks!

**Comment by neuecc** [comment]
released v2.0.1

**Comment by ES0T** [comment]
Awesome. Thanks for fast update. Works well.
