### ISSUE TITLE
error:LibGit2SharpException on Visual Studio 2022, Version 17.11.4

### ISSUE THREAD

**Issue by KeyC0de** [neuecc/Open-on-GitHub#27]
![image](https://github.com/user-attachments/assets/7231c2d7-0812-4039-8078-c1c70d71bbb4)

**Comment by ycherkes** [comment]
@KeyC0de You can check if you wish this version of the extension - I replaced LibGit2Sharp with [GitReader](https://github.com/kekyo/GitReader)

[PR!28](https://github.com/neuecc/Open-on-GitHub/pull/28)

[OpenOnGitHub.zip](https://github.com/user-attachments/files/17622901/OpenOnGitHub.zip)

**Comment by KeyC0de** [comment]
Thank you kindly. It works.

**Comment by KeyC0de** [comment]
Thank you kindly. It works.

**Comment by neuecc** [comment]
thx, officialy released PR(v2.1.0).
