### ISSUE TITLE
Add line number to GitHub links

### ISSUE THREAD

**Issue by jcansdale** [neuecc/Open-on-GitHub#6]
Hello,

Nice extension! 😄 

I wonder if you could add the line number to your GitHub URLs. Eg jump to line 15 with `#L15`:
https://github.com/neuecc/Open-on-GitHub/blob/master/OpenOnGitHub/Constants.cs#L15

Cheers,
Jamie.

**Comment by neuecc** [comment]
Maybe it is already supported?
