### ISSUE TITLE
Stopped working after upgrade to 1.4.1

### ISSUE THREAD

**Issue by judocode** [neuecc/Open-on-GitHub#7]
I just upgraded to `1.4.1`  (not sure of the version before that but it should have been the latest), and now nothing happens when I attempt to use Open on Github.

I am running Visual Studio 2013 Professional

Were there breaking changes or anything else to be aware of?

**Comment by neuecc** [comment]
Visual Studio 2017's VSIX reference has many changes,
https://github.com/neuecc/Open-on-GitHub/commit/edc55424deb03109a1acaa9478ddb85572fff9cc
Perhaps it has destroyed the old environment.
I do not know unless examine it in detail.

**Comment by judocode** [comment]
@neuecc Is there a way to download the previous version so I can get it working again?

**Comment by gregmulvihill** [comment]
@jrenton - Download, build, and install a previous commit...

1. https://github.com/neuecc/Open-on-GitHub
2. Click '35 commits'
3. At the end of the row titled 'Commits on Dec 28, 2015', click '<>'
4. Click the green button titled 'Clone of download'
5. Click 'Download ZIP'
6. Unzip and build a Release with VS 2015
7. Exit VS2015
8. Open OpenOnGitHub\bin\Release and launch OpenOnGitHub.vsix

**Comment by judocode** [comment]
@gregmulvihill Thanks so much for your detailed instructions. The problem is that it is broken in 2013 and I am unable to open it in 2013. I've tried building it in 2015 on my home PC as well but when I built it, it still didn't work in 2013. Here is the release I created: https://github.com/jrenton/Open-on-GitHub/releases

**Comment by gregmulvihill** [comment]
@jrenton Unfortunately I do not have VS2013 installed, so I am shooting in the dark.  

When I open a solution/project with the 1.4.1 release of OpenOnGithub in VS2015, I get a dialog pointing me to C:\Users\XXX\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml, with the last entry - "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."  Maybe a clue for your build environment?

Will any of the older commits build in VS2013 for you?  

I could not find a way to download a previous release of the .visx file.  :(  

I'll poke around this weekend and post anything useful I discover.
